import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Contact from '../components/Contact'
import Products from '../components/Products'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Banting Communication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <Products />
      {/* <Contact /> */}
    </div>
  )
}

export default Home
