import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Contact from '../components/Contact'
import Products from '../components/Products'
import Reviews from '../components/Reviews'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Banting Communication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <Products />
      <Reviews />
      <Contact />
    </div>
  )
}

export default Home
